Add, installation disk space requirements calculation, improve README, add multipass workflows

diff --git a/.github/workflows/ubuntu-24.04.yml b/.github/workflows/ubuntu-24.04.yml
--- a/.github/workflows/ubuntu-24.04.yml
+++ b/.github/workflows/ubuntu-24.04.yml
@@ -19,6 +19,9 @@ jobs:
     steps:
     - uses: actions/checkout@v4
 
+    - name: Store initial disk space
+      run: echo avail_df[\$(date '+%d.%m.%Y %H:%M:%S')]=\$(df . --output=avail | tail -n 1) > vminfo.initial
+
     - name: Create virtual environment
       run: |
         sudo apt install python3-venv
@@ -62,3 +65,14 @@ jobs:
         label: Code coverage
         message: "${{ steps.coverage.outputs.coverage }}%"
         color: ${{ steps.coverage.outputs.coverage >= 80 && 'green' || steps.coverage.outputs.coverage >= 70 && 'yellow' || 'red' }}
+
+    - name: Report of disk usage
+      run: |
+        initial_avail_space=$(cat vminfo.initial | grep '^avail_df' | sed 's/.*=\s*\(.*\)/\1/'")
+        echo "Initial avail space: $initial_avail_space"
+        final_avail_space=$(cat vminfo.final | grep '^avail_df' | sed 's/.*=\s*\(.*\)/\1/'")
+        echo "Final avail space: $final_avail_space"
+        consumed_space_raw=$(($initial_avail_space - $final_avail_space))
+        echo "Consumed space raw: $consumed_space_raw"
+        consumed_space_human=$(numfmt --to=si $(($consumed_space_raw*1000))) || echo "Failed to convert to human readable space"
+        echo "Consumed space human: $consumed_space_human"
